test = """
..............
..............
..............
..............
..............
..............
....XXXXXX....
...XX....XX...
...XX....XX...
...XX....XX...
...XX....XX...
...XX....XX...
...XX....XX...
...XX....XX...
...XX....XX...
...XX....XX...
...XX....XX...
....XXXXXX....
..............
..............
..............
..............
..............
..............
..............
..............
"""

H = """
..............
..............
..............
..............
..............
..............
...XX....XX...
...XX....XX...
...XX....XX...
...XX....XX...
...XX....XX...
...XXXXXXXX...
...XX....XX...
...XX....XX...
...XX....XX...
...XX....XX...
...XX....XX...
...XX....XX...
..............
..............
..............
..............
..............
..............
..............
..............
"""

Y = """
..............
..............
..............
..............
..............
..............
...XX....XX...
...XX....XX...
...XX....XX...
...XX....XX...
....X....X....
.....X..X.....
......XX......
......XX......
......XX......
......XX......
......XX......
....XXXXXX....
..............
..............
..............
..............
..............
..............
..............
..............
"""

P = """
..............
..............
..............
..............
..............
..............
...XXXXXXX....
...XX....XX...
...XX....XX...
...XX....XX...
...XX....XX...
...XX....XX...
...XXXXXXX....
...XX.........
...XX.........
...XX.........
...XX.........
...XX.........
..............
..............
..............
..............
..............
..............
..............
..............
"""

E = """
..............
..............
..............
..............
..............
..............
...XXXXXXX....
...XX.........
...XX.........
...XX.........
...XX.........
...XX.........
...XXXXXX.....
...XX.........
...XX.........
...XX.........
...XX.........
...XXXXXXX....
..............
..............
..............
..............
..............
..............
..............
..............
"""

def midoval(x, y, r):
    oval(x - r / 2, y - r / 2, r, r)


def midrect(x, y, r):
    rect(x - r / 2, y - r / 2, r, r)


def pixelizer(letter, pixelSize, whichFrame):
    y = 2000
    for row in letter.splitlines():
        x = 0
        for pixel in row:
            if pixel == "X":
                midoval(x, y, (nFrames - whichFrame) * pixelSize / nFrames * .8)
            elif pixel == ".":
                midoval(x, y, whichFrame * pixelSize / nFrames * .8)
            x += pixelSize
        y -= pixelSize

pixel = 80
fRate = 12
nFrames = 8

for frame in range(nFrames):
    newPage(1080, 1920)
    frameDuration(1/fRate)
    fill(0.1)
    rect(0, 0, width(), height())
    fill(0, 0.9, 0.2)
    translate(pixel/4, 0)
    pixelizer(H, pixel, frame)

for frame in range(nFrames):
    newPage(1080, 1920)
    frameDuration(1/fRate)
    fill(0.1)
    rect(0, 0, width(), height())
    fill(0, 0.9, 0.2)
    translate(pixel/4, 0)
    pixelizer(H, pixel, nFrames-frame)

for frame in range(nFrames):
    newPage(1080, 1920)
    frameDuration(1/fRate)
    fill(0.1)
    rect(0, 0, width(), height())
    fill(0, 207/255, 1)
    translate(pixel/4, 0)
    pixelizer(Y, pixel, frame)

for frame in range(nFrames):
    newPage(1080, 1920)
    frameDuration(1/fRate)
    fill(0.1)
    rect(0, 0, width(), height())
    fill(0, 207/255, 1)
    translate(pixel/4, 0)
    pixelizer(Y, pixel, nFrames-frame)

for frame in range(nFrames):
    newPage(1080, 1920)
    frameDuration(1/fRate)
    fill(0.1)
    rect(0, 0, width(), height())
    fill(1, 1, 0.2)
    translate(pixel/4, 0)
    pixelizer(P, pixel, frame)

for frame in range(nFrames):
    newPage(1080, 1920)
    frameDuration(1/fRate)
    fill(0.1)
    rect(0, 0, width(), height())
    fill(1, 1, 0.2)
    translate(pixel/4, 0)
    pixelizer(P, pixel, nFrames-frame)

for frame in range(nFrames):
    newPage(1080, 1920)
    frameDuration(1/fRate)
    fill(0.1)
    rect(0, 0, width(), height())
    fill(1, 59/255, 74/255)
    translate(pixel/4, 0)
    pixelizer(E, pixel, frame)

for frame in range(nFrames):
    newPage(1080, 1920)
    frameDuration(1/fRate)
    fill(0.1)
    rect(0, 0, width(), height())
    fill(1, 59/255, 74/255)
    translate(pixel/4, 0)
    pixelizer(E, pixel, nFrames-frame)


saveImage("_exp/29_HYPE.gif")
